Add new zsh completion and update README.md
pimterry/notes pull request #33
Opened 2016-12-13 02:50 UTC by RODNOTGOD

2016-12-13 03:05 UTC, primis commented
Maybe make authors of that "pimterry et al."?

2016-12-13 03:06 UTC, RODNOTGOD commented
sure thing

2016-12-19 23:04 UTC, pimterry requested changes
Thanks so much for doing this! I like zsh, but I've never written a Zsh completion script, so I was somewhat dreading having to try and wade through this, this is a great help. I've added notes for a few tweaks inline. 

I'm also interested in testing, which I know might not be what you want to hear. We did manage to get it working very nicely for the bash autocompletion though (https://github.com/pimterry/notes/blob/master/test/test-bash-completion.bats) which gives me some hope it might be doable, and at least getting a couple of tests in would be a huge boost to my confidence that we'll be able to keep this working reliably in future!

2016-12-19 23:04 UTC, pimterry commented on README.md
> +```
We've kind of interleaved the two sets of setup here: you need bash or zsh, here's the bash dir here's the zsh dir, here's the bash commands here's the zsh commands. We should just split this into two sections.

2016-12-19 23:04 UTC, pimterry commented on _notes
> +#  * pimterry et al.
You're more than welcome to add a link to https://github.com/pimterry/notes/graphs/contributors, which would give people credit a little more directly :smile:.

2016-12-19 23:04 UTC, pimterry commented on _notes
> +    --help:'Show usage'
We now also have 'search' here, as of #16

2016-12-19 23:04 UTC, pimterry commented on _notes
> +        _path_files -W "${note_dir}" -/ && _ret=0;;
Find and search should probably auto complete paths too?

2016-12-19 23:04 UTC, pimterry commented on _notes
> +# vim: ft=zsh sw=2 ts=2 et
I'd rather not have these in here inline. I'd be quite open to a separate PR adding a [.editorconfig](http://editorconfig.org/) file or something though.

2016-12-20 03:50 UTC, RODNOTGOD commented on _notes
> +# vim: ft=zsh sw=2 ts=2 et
This portion of the comments were for the [zsh-completion](https://github.com/zsh-users/zsh-completions) repo. It was part of their guide lines, but this depends mostly if you wanted this to be added to the zsh-completions repo.

2016-12-20 03:50 UTC, RODNOTGOD commented on _notes
> +        _path_files -W "${note_dir}" -/ && _ret=0;;
Alright sounds good

2016-12-20 03:52 UTC, RODNOTGOD commented
I'll work on the tweaks. On the bats test I'm a little iffy on them; simply because bats doesn't play nicely with zsh and zsh completions don't behave life bash scripts and outputs.

2016-12-20 09:34 UTC, pimterry commented
You don't need to close this PR, you can just push more commits to the same branch, and they'll magically appear here too :smile:.

That is a good argument against zsh completions, I must admit. If we could get even the basics to check that it hasn't been fundamentally broken in future that would be useful though. https://github.com/bamarni/symfony-console-autocomplete might be worth a look - it's a project including autocomplete for zsh and bash, with a basic set of bats tests for both that might be helpful, and which seem to work. Have a go, see what happens.

2017-01-29 17:19 UTC, pimterry commented
@RODNOTGOD Any thoughts on this? I'd love to get this merged soon if possible.

2017-02-04 15:10 UTC, RODNOTGOD commented
Hey sorry for the extended delay, college picked up again and I've been busy. Now regarding the auto-complete issue. It seems to be that there no effective way to correctly emulate the zsh tests for correct auto  completion. The symfony-autocomplete looked promising, but turns out only can test for zsh file generation. I looked at other testing methods, but most seem to implement also a file generation. So to conclusion, We can either push the zsh without testing; and zsh tends not to break anything, but does goes against what you see for the project. Or we push this to [zsh-completions](https://github.com/zsh-users/zsh-completions) repository, but creates a divergence in the project now D:.

2017-02-12 22:33 UTC, pimterry commented
@RODNOTGOD Ok - I'm happy to ignore automated zsh testing for the moment then. Let's just finish up the rest of the comments left on here, and then it's ready to go.

2017-02-12 22:37 UTC, RODNOTGOD commented
Ok, sounds good to me. I'll update the pull request by today or tomorrow.

2017-04-02 10:17 UTC, pimterry approved these changes

2017-04-02 10:17 UTC, merged