feat: Add shorthand cat alias c
pimterry/notes pull request #90
Opened 2023-04-06 12:33 UTC by allank-fd

# Fixes # 

### Checklist
- [ ] I have made a change to this repository, be it functionality, testing, documentation, spelling, or grammar.
- [ ] I updated my branch with the master branch.
- [ ] I have added the necessary testing to prove my fix is effective/my feature works (or I did not modify functionality).
- [ ] I have added necessary documentation about the functionality in an appropriate .md file.
- [ ] I have appropriately commented any code I have modified

### Short description of what this PR does:
- 
-

2023-04-06 15:09 UTC, pimterry requested changes
It looks like you've reformatted and tweaked lots of unrelated code here, in both the tests and the core script. Can you remove all the changes that aren't required for this PR please, and squash the result back to a single commit? It's very useful to keep commits & PRs to a single set of changes.

I'm open to other changes too, but if you're doing that then it'd be helpful if you could open a separate PR for them, and provide some background on what you're trying to do there & why.

2023-04-06 15:09 UTC, pimterry commented on README.md
> +Shorthand alias also available with `notes c`.
I think it'd be better to put this after the description of the command (i.e. as a second sentence in the paragraph below. Makes more sense that way, and it's consistent with the rest of the documentation here.

2023-04-12 12:44 UTC, allank-fd commented
@pimterry Thanks for the feedback, I've updated the PR to remove the formatting changes. Plus the small change to the Readme to keep it inline with the other command docs.

2023-04-14 10:50 UTC, pimterry approved these changes

2023-04-14 10:50 UTC, merged

2023-04-14 10:51 UTC, pimterry commented
Nice work, thanks! Merged :+1: